

services:
  rag-api:
    build:
      context: .
    container_name: rag-api
    ports:
      - "8500:8500"
    volumes:
      - ./app:/app
    working_dir: /app  # Add this to set the working dir inside container
    env_file:
      - .env
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: rag-ui
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - rag-api
    env_file:
      - .env

